version: '3.7'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=dockerexpress
      - POSTGRESQL_PASSWORD=dockerexpress
      - POSTGRESQL_DATABASE=apiexpress
